export const REQUEST_CLUB_LIST = 'REQUEST_CLUB_LIST';
export const REQUEST_CLUB_LIST_SUCCESS = 'REQUEST_CLUB_LIST_SUCCESS';
export const REQUEST_CLUB_LIST_FAIL = 'REQUEST_CLUB_LIST_FAIL';

export const REQUEST_CLUB = 'REQUEST_CLUB';
export const REQUEST_CLUB_SUCCESS = 'REQUEST_CLUB_SUCCESS';
export const REQUEST_CLUB_FAIL = 'REQUEST_CLUB_FAIL';