export const REQUEST_EVENT_LIST = 'REQUEST_EVENT_LIST';
export const REQUEST_EVENT_LIST_SUCCESS = 'REQUEST_EVENT_LIST_SUCCESS';
export const REQUEST_EVENT_LIST_FAIL = 'REQUEST_EVENT_LIST_FAIL';

export const REQUEST_EVENT = 'REQUEST_EVENT';
export const REQUEST_EVENT_SUCCESS = 'REQUEST_EVENT_SUCCESS';
export const REQUEST_EVENT_FAIL = 'REQUEST_EVENT_FAIL';