export const REQUEST_DATA_START = "REQUEST_DATA_START";
export const REQUEST_DATA_SUCCESS = "REQUEST_DATA_SUCCESS";
export const REQUEST_DATA_FAIL = "REQUEST_DATA_FAIL";

export const CREATE_DATA_START = "CREATE_DATA_START";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const CREATE_DATA_FAIL = "CREATE_DATA_FAIL";

export const UPDATE_DATA_START = "UPDATE_DATA_START";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const UPDATE_DATA_FAIL = "UPDATE_DATA_FAIL";

export const REMOVE_DATA_START = "REMOVE_DATA_START";
export const REMOVE_DATA_SUCCESS = "REMOVE_DATA_SUCCESS";
export const REMOVE_DATA_FAIL = "REMOVE_DATA_FAIL";