export const REQUEST_DATA = "REQUEST_DATA";
export const REQUEST_DATA_SUCCESS = "REQUEST_DATA_SUCCESS";
export const REQUEST_DATA_FAIL = "REQUEST_DATA_FAIL";

export const CREATE_DATA = "CREATE_DATA";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const CREATE_DATA_FAIL = "CREATE_DATA_FAIL";

export const UPDATE_DATA = "UPDATE_DATA";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const UPDATE_DATA_FAIL = "UPDATE_DATA_FAIL";

export const REMOVE_DATA = "REMOVE_DATA";
export const REMOVE_DATA_SUCCESS = "REMOVE_DATA_SUCCESS";
export const REMOVE_DATA_FAIL = "REMOVE_DATA_FAIL";